# Intro to Python for DLW

The SilverPond DLW will be taught using Python, Numpy and Tensorflow. The content will be presented via Jupyter Notebooks (you're in one)...how to notebook


In [1]:
# importing libraries
import numpy as np
import tensorflow as tf

Tuples and Lists

In [2]:
'''Tuples are defined using (parentheses)'''
two_ele_tuple        = (20, 21)
one_ele_tuple        = (22,)        # Note this is not the same as (22). The trailing ',' tells python to treat this as a tupel and NOT a number that is just in parentheses.
a_num_in_parentheses = (24)         # NOT a tuple!

print("two_ele_tuple: {}".format(two_ele_tuple))
print("one_ele_tuple: {}".format(one_ele_tuple))
print("a_num_in_parentheses: {}".format(a_num_in_parentheses))

two_ele_tuple: (20, 21)
one_ele_tuple: (22,)
a_num_in_parentheses: 24


In [3]:
'''Lists are defined by [square braces]'''
two_ele_list        = [20, 21]
one_ele_list        = [22,]        # Note the trailing ',' is not nessessary when declaring lists.
also_a_one_ele_list = [24]         # Also a list

print("two_ele_list: {}".format(two_ele_list))
print("one_ele_list: {}".format(one_ele_list))
print("also_a_one_ele_list: {}".format(also_a_one_ele_list))

two_ele_list: [20, 21]
one_ele_list: [22]
also_a_one_ele_list: [24]


In [4]:
'''Tuples and lists are indexable'''
tup0  = (2,3,4)
list0 = [5,6,7] 
print("idx 1 of tup0: {}".format(tup0[1]))
print("idx 1 of list0: {}".format(list0[1]))

idx 1 of tup0: 3
idx 1 of list0: 6


In [5]:
'''Tuples can have more than one data type. Lists cannot'''
tup1 = (1, "one", 3.14159, [1,2,3])
print("idx 0: {}".format(tup1[0]))
print("idx 1: {}".format(tup1[1]))
print("idx 2: {}".format(tup1[2]))
print("idx 3: {}".format(tup1[3]))
print("idx 1 of tup1[3]: {}".format(tup1[3][1]))

idx 0: 1
idx 1: one
idx 2: 3.14159
idx 3: [1, 2, 3]
idx 1 of tup1[3]: 2


In [6]:
'''List elements can be over-written'''
list1 = [1,2,3]
print("list1: {}".format(list1))
list1[0] = 4
print("list1: {}".format(list1))

list1: [1, 2, 3]
list1: [4, 2, 3]


In [7]:
'''Tuples are immutable'''
tup2 = (1,2,3)
tup2[0] = 4
'''THIS WILL THROW AN ERROR'''

TypeError: 'tuple' object does not support item assignment

In [8]:
'''If you wanted to change tup2[0] to 4 you would need to do this'''
tup2 = (1,2,3)
print("tup2: {}".format(tup2))
tup2 = (4,2,3)
print("tup2: {}".format(tup2))

tup2: (1, 2, 3)
tup2: (4, 2, 3)


# Slicing

Slicing is a great tool. It allows us to access ranges of elements with lists in a compact fashion. However, somtimes it can become a bit confsing. We'll introduce it in small steps.


In [9]:
'''Both lists and tuples can be sliced.'''
# index  0   1   2   3   4   5   6   7   8   9
list0 = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
tup0  = (20, 21, 22, 23, 23, 25, 26, 27, 28, 29)

a = list0[1:5]    # slice from idx 1 to idx 4 (the ending idx in NOT inclusice) the reason will make sense later
b = tup0[1:5]

print("slice of list0: {}".format(a))
print("slice of tup0 : {}".format(b))

slice of list0: [11, 12, 13, 14]
slice of tup0 : (21, 22, 23, 23)


In [10]:
'''
Because we'll be primarilly working with lists in 
the worksope we'll just work with lists for not,
but all these oporations
are valid with tuples too.
'''

'''The 2 oporations below are equivalent'''
c = list0[0:3]
d = list0[:3]
print("c: {}".format(c))
print("d: {}\n".format(d))

'''The 2 oporations below are also equivalent'''
e = list0[3:10]   # Note: Because the 10 is not inclusive we are not indexing outside the array
                  #       but this can be confusing so the following syntax is prefered
f = list0[3:]  
print("e: {}".format(e))
print("f: {}\n".format(f))

'''Using negitave indexes allow you to access elements from the end of the list'''
g = list0[9]
h = list0[-1]         # This is a handy way to access the last element of a list
i = list0[6]
j = list0[-4]
print("g: {}".format(g))
print("h: {}".format(h))
print("i: {}".format(i))
print("j: {}".format(j))

c: [10, 11, 12]
d: [10, 11, 12]

e: [13, 14, 15, 16, 17, 18, 19]
f: [13, 14, 15, 16, 17, 18, 19]

g: 19
h: 19
i: 16
j: 16


In [11]:
'''
You can also slice in steps (ie: every 2nd element)

'''
# Just redefining list0 for reference.
list0 = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

a = list0[1:8:2]
print("a: {}".format(a))

'''
If we omit the 8 we can take evey 2nd element,
starting at index 1 and going to the end
'''
b = list0[1::2]
print("b: {}".format(b))

'''
If we omit the 1 we can take every 2nd element
starting at the 0th element and going to the end.
'''
c = list0[::2]
print("c: {}".format(c))

'''We can even go in reverse'''
d = list0[-1:0:-2]
print("d: {}".format(d))

a: [11, 13, 15, 17]
b: [11, 13, 15, 17, 19]
c: [10, 12, 14, 16, 18]
d: [19, 17, 15, 13, 11]


Python list vs Numpy array.

In [12]:
'''Stock standard python lists'''
my_list = [10, 11, 12, 13]
list_of_lists = [[10, 11],[12,13]]

'''numpy arrays are declared like so'''
my_np_array = np.array([10, 11, 12, 13])
my_2n_np_array = np.array([[10, 11],[12, 13]])

zeros = np.zeros([2,2])
print(zeros)

ones = np.ones([3,3])
print(ones)

'''Broadcasting'''
np_fives = ones*5
print(fives)

'''
    Note this oporation does not have the same behaviour
    when using python lists
'''
 
py_fives = [1,1,1,1,1]*5
print(my_other_list)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


NameError: name 'fives' is not defined

Array Shape

In [ ]:
print(np.shpae(x))

Array slicing

In [5]:
a = my_list[4]
b = my_list[-1]